trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
      addToPath: true

  - script: |
      python -m pip install --upgrade pip
    displayName: 'Install pip'

  - script: |
      python -m unittest test_app.py
    displayName: 'Run Unittest Tests'
